import express from 'express';
import{createAppointment} from '../Controller/AppointmentController.js';
import authMiddleware from '../Middleware/authMiddleware.js';
import ClientMiddleware from '../Middleware/ClientMiddleware.js';
import { CancelAppointment , CompleteAppointment} from '../Controller/AppointmentController.js';
const router = express.Router();
router.post('/create/:freelancerId', authMiddleware, ClientMiddleware, createAppointment);
router.patch('/:id/cancel', authMiddleware, CancelAppointment);
router.patch('/:id/complete',authMiddleware,CompleteAppointment);
export default router;